from nets.gcnn import *
from nets.fine_grain import *
from nets.blocks import *
from nets.gcnn_bap_cbam import *
from nets.gcnn_bap import *
from nets.gcnn_cbam import *
from nets.gcnn_bottle import *
from nets.gcnn_bap_cbam_bottle import *
from nets.other.resnet50 import *
from nets.other.zhang import *
from nets.other.henet import *
